import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { AiFillCar, AiFillSafetyCertificate } from "react-icons/ai";
import Navbar from '@/Components/Navbar'
import L1 from '../img/L1.png'
import {BsFillBuildingsFill} from "react-icons/bs"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="bgimage  sm:h-[100vh] lg:h-[70vh]">
				<Navbar />
				<section class="text-white body-font">
					<div class="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
						<div class="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center ">
							<h1 class="text-[50px] mb-4 font-medium text-white">
								Welcome To RideShare
							</h1>
							<p class="mb-8 leading-relaxed text-[25px]">
								Everywhere and for everyone. Ride or drive, shop or deliver,
								send or receive with RideShare — offer-your-price mobility app
								for fair deals
							</p>
							<div class="flex justify-center">
								<button class=" drop-shadow-2xl inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded ">
									Download App
								</button>
								<button class=" drop-shadow-2xl ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded ">
									Contact us
								</button>
							</div>
						</div>
						<div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
							<div class="object-cover object-center rounded drop-shadow-2xl"></div>
							<Image className="drop-shadow-2xl" alt="hero" src={L1} />
						</div>
					</div>
				</section>
			</div>
			<section className="bgimage2 sm:h-[100vh] lg:h-[70vh]">
				<div className="container-fluid">
					<h1 className="text-center text-white text-[50px] mb-10 py-10 ">
						Our Services
					</h1>
					<div className="row ml-[10%]">
						<div className="col-md-4 mb-3">
							<div class="card drop-shadow-2xl" style={{ width: "12rem" }}>
								<AiFillCar
									size={40}
									style={{ marginTop: "5%", marginLeft: "40%" }}
									color="00639A"
								/>
								<div class="card-body">
									<h5 class="card-title text-center font-bold">City Rides</h5>
								</div>
							</div>
						</div>
						<div className="col-md-4  mb-3">
							<div class="card drop-shadow-2xl" style={{ width: "12rem" }}>
								<BsFillBuildingsFill
									size={40}
									style={{ marginTop: "5%", marginLeft: "40%" }}
									color="00639A"
								/>
								<div class="card-body">
									<h5 class="card-title text-center font-bold">
										Inter City Rides
									</h5>
								</div>
							</div>
						</div>
						<div className="col-md-4  mb-3">
							<div class="card drop-shadow-2xl" style={{ width: "12rem" }}>
								<AiFillSafetyCertificate
									size={40}
									style={{ marginTop: "5%", marginLeft: "40%" }}
									color="00639A"
								/>
								<div class="card-body">
									<h5 class="card-title text-center font-bold">
										Safety First{" "}
									</h5>
								</div>
							</div>
						</div>
					</div>
					<div className="row  mt-20 py-10 pl-[10%] bgcolor">
						<div className="col-md-3  mb-3">
							<h1 className="text-[#00639A] font-bold">Human Prosperity</h1>
						</div>
						<div className="col-md-3  mb-3">
							<h1 className="text-[#00639A] font-bold">
								Community Development
							</h1>
						</div>
						<div className="col-md-3  mb-3">
							<h1 className="text-[#00639A] font-bold">Planet Care</h1>
						</div>
						<div className="col-md-3">
							<h1 className="text-[#00639A] font-bold">Quality of life</h1>
						</div>
					</div>
				</div>
			</section>
		</>
	);
}
